name: segCNN
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _tflow_select=2.3.0=eigen
  - absl-py=0.11.0=pyhd3eb1b0_1
  - aiohttp=3.6.3=py38h7b6447c_0
  - astunparse=1.6.3=py_0
  - async-timeout=3.0.1=py38h06a4308_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - blas=2.14=openblas
  - blinker=1.4=py38h06a4308_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2020.12.5=ha878542_0
  - cachetools=4.2.1=pyhd3eb1b0_0
  - cairo=1.16.0=h7979940_1007
  - certifi=2020.12.5=py38h578d9bd_1
  - cffi=1.14.4=py38h261ae71_0
  - chardet=3.0.4=py38h06a4308_1003
  - click=7.1.2=pyhd3eb1b0_0
  - cryptography=3.3.1=py38h3c74f83_0
  - cycler=0.10.0=py38_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.2.10=he6710b0_2
  - ffmpeg=4.3.1=hca11adc_2
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - gast=0.3.3=py_0
  - gettext=0.19.8.1=h0b5b191_1005
  - glib=2.66.6=h9c3ff4c_3
  - glib-tools=2.66.6=h9c3ff4c_3
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - google-auth=1.24.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.2=pyhd3eb1b0_2
  - google-pasta=0.2.0=py_0
  - graphite2=1.3.13=h58526e2_1001
  - grpcio=1.31.0=py38hf8bcb03_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.18.3=h3560a44_0
  - h5py=2.10.0=py38hd6299e0_1
  - harfbuzz=2.7.4=h5cf4720_0
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=68.1=h58526e2_0
  - idna=2.10=pyhd3eb1b0_0
  - importlib-metadata=2.0.0=py_1
  - intel-openmp=2020.2=254
  - jasper=1.900.1=h07fcdf6_1006
  - jpeg=9d=h36c2ea0_0
  - keras=2.4.3=0
  - keras-base=2.4.3=py_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.3.1=py38h2531618_0
  - krb5=1.17.2=h926e7f8_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.35.1=hcecfb41_1
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libclang=11.0.1=default_ha53f305_1
  - libedit=3.1.20191231=h14c3975_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h9cbead1_17
  - libgfortran-ng=7.5.0=hae1eefd_17
  - libgfortran4=7.5.0=hae1eefd_17
  - libglib=2.66.6=h1f3bc88_3
  - libgomp=9.3.0=h9cbead1_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.8.0=14_openblas
  - liblapacke=3.8.0=14_openblas
  - libllvm11=11.0.1=hf817b99_0
  - libopenblas=0.3.7=h5ec1e0e_6
  - libopencv=4.5.1=py38h703c3c0_0
  - libpng=1.6.37=hbc83047_0
  - libpq=12.3=h255efa7_3
  - libprotobuf=3.14.0=h8c45485_0
  - libstdcxx-ng=9.3.0=h2ae2ef3_17
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libwebp-base=1.2.0=h7f98852_0
  - libxcb=1.14=h7b6447c_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.10=h72842e0_3
  - lz4-c=1.9.3=h2531618_0
  - markdown=3.3.3=py38h06a4308_0
  - matplotlib=3.3.2=h06a4308_0
  - matplotlib-base=3.3.2=py38h817c723_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.2.0=py38hab2c0dc_1
  - mkl_random=1.2.0=py38hc5bc63f_1
  - multidict=4.7.6=py38h7b6447c_1
  - mysql-common=8.0.22=ha770c72_1
  - mysql-libs=8.0.22=h1fd7589_1
  - ncurses=6.2=he6710b0_1
  - nettle=3.6=he412f7d_0
  - nspr=4.29=h9c3ff4c_1
  - nss=3.61=hb5efdd6_0
  - numpy=1.20.0=py38h18fd61f_0
  - numpy-base=1.18.5=py38h2f8d375_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py_0
  - opencv=4.5.1=py38h578d9bd_0
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1i=h7f98852_0
  - opt_einsum=3.1.0=py_0
  - pcre=8.44=he6710b0_0
  - pillow=8.1.0=py38he98fc37_0
  - pip=20.3.3=py38h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - protobuf=3.14.0=py38h2531618_1
  - py-opencv=4.5.1=py38h81c977d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pyjwt=1.7.1=py38_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.12.3=py38ha8c2ead_4
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.8=1_cp38
  - pyyaml=5.4.1=py38h27cfd23_1
  - qt=5.12.9=h9d6b050_2
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7=pyhd3eb1b0_1
  - scipy=1.5.3=py38h828c644_0
  - setuptools=52.0.0=py38h06a4308_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py38h06a4308_0
  - sqlite=3.34.0=h74cdb3f_0
  - tensorboard=2.3.0=pyh4dce500_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.3.0=eigen_py38h71ff20e_0
  - tensorflow-base=2.3.0=eigen_py38hb57a387_0
  - tensorflow-estimator=2.3.0=pyheb71bc4_0
  - termcolor=1.1.0=py38_1
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.56.0=pyhd3eb1b0_0
  - urllib3=1.26.3=pyhd3eb1b0_0
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - wrapt=1.12.1=py38h7b6447c_1
  - x264=1!161.3030=h7f98852_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.2=h470a237_5
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.6.3=py38h27cfd23_0
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
prefix: /home/mazharul/anaconda3/envs/segCNN
